version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"